version: "3.7"

services:
  postgres12:
    image: "postgres:12" # use latest official postgres version
    container_name: postgres12
    env_file:
      - postgres/database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./sqls/:/home/postgres/databases/ # persist databases
    ports:
      - '5432:5432' # expose port 5432 on host
    command: ["postgres", "-c", "log_statement=all"] # start postgres with logging enabled
    restart: always
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      - postgres12
    restart: always
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: general
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 6060:80
    environment:
      - PMA_ARBITRARY=1
  php7_4:
    container_name: php7_4
    build:
      context: ./php/7_4
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  php5_6:
    container_name: php5_6
    build:
      context: ./php/5_6
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8001:80
volumes:
  database-data: # named volumes can be managed easier using docker-compose
networks:
  default:
    driver: bridge
    name: common