version: "3.7"

services:
  postgres12:
    image: "postgres:12" # use latest official postgres version
    container_name: postgres12
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./sqls/:/home/postgres/databases/ # persist databases
    ports:
      - '5432:5432' # expose port 5432 on host
    restart: always
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      - postgres12
    restart: always
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    restart: always
volumes:
  database-data: # named volumes can be managed easier using docker-compose
networks:
  default:
    driver: bridge
    name: common